AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for deploying the OpenMarket API

Globals:
  Function:
    # Timeout needs to be higher than the default 3 seconds
    Timeout: 10
    MemorySize: 128

Parameters:
  ProxyHost:
    Type: String
    Description: The host URL for your forward proxy
    Default: ""
  ProxyUsername:
    Type: String
    Description: The username for your forward proxy
    Default: ""
  ProxyPassword:
    Type: String
    Description: The password for your forward proxy
    Default: ""

Resources:
  OpenMarketFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: api/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        # If testing locally on an M-series Mac, use arm64 architecture
        - arm64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /l/{id}
            Method: POST
      Environment:
        Variables:
          PROXY_HOST: !Ref ProxyHost
          PROXY_USERNAME: !Ref ProxyUsername
          PROXY_PASSWORD: !Ref ProxyPassword

Outputs:
  OpenMarketAPI:
    Description: "API Gateway endpoint URL for Prod environment for OpenMarket Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/l/{id}"
  OpenMarketFunction:
    Description: "OpenMarket Lambda Function ARN"
    Value: !GetAtt OpenMarketFunction.Arn
  OpenMarketFunctionIamRole:
    Description: "Implicit IAM Role created for OpenMarket function"
    Value: !GetAtt OpenMarketFunctionRole.Arn
